package SrdLang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Feature_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new FeatureReference_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Screen_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new TestCase_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new TestCaseReference_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new UseCase_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new UseCaseReference_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new FeatureReference_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new TestCaseReference_SubstituteMenu());
      case 2:
        return Collections.<SubstituteMenu>singletonList(new UseCaseReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f7004aL), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70053L), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70068L), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70035L), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70041L), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70059L), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70061L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70053L), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70041L), MetaIdFactory.conceptId(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70061L)).seal();
}
