package SrdLang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import SrdLang.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Feature:
        return new Feature_TextGen();
      case LanguageConceptSwitch.FeatureReference:
        return new FeatureReference_TextGen();
      case LanguageConceptSwitch.Screen:
        return new Screen_TextGen();
      case LanguageConceptSwitch.TestCase:
        return new TestCase_TextGen();
      case LanguageConceptSwitch.TestCaseReference:
        return new TestCaseReference_TextGen();
      case LanguageConceptSwitch.UseCase:
        return new UseCase_TextGen();
      case LanguageConceptSwitch.UseCaseReference:
        return new UseCaseReference_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(MetaAdapterFactory.getConcept(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70068L, "SrdLang.structure.Screen"))) {
        String fname = getFileName_Screen(root);
        String ext = getFileExtension_Screen(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_Screen(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_Screen(SNode node) {
    return null;
  }
}
