package SrdLang.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import SrdLang.behavior.ICoverable__BehaviorDescriptor;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;

public class UseCase_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.indent();
    tgs.append("Use Case ");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    tgs.append(" (" + (double) ICoverable__BehaviorDescriptor.coverage_id7Q3cUQn2IQX.invoke(ctx.getPrimaryInput()) + "%)");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70059L, 0x5d28744d28f7005cL, "features"))).isNotEmpty()) {
      tgs.indent();
      tgs.append("Features");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70059L, 0x5d28744d28f7005cL, "features"))) {
        tgs.appendNode(item);
      }
      ctx.getBuffer().area().decreaseIndent();
    }
    if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70059L, 0x5d28744d28f7005eL, "featureReferences"))).isNotEmpty()) {
      tgs.indent();
      tgs.append("Feature References");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x1ebab0354f0e4c1aL, 0x81628b734f2fc0d1L, 0x5d28744d28f70059L, 0x5d28744d28f7005eL, "featureReferences"))) {
        tgs.appendNode(item);
      }
      ctx.getBuffer().area().decreaseIndent();
    }
    ctx.getBuffer().area().decreaseIndent();
  }
}
